/*
 * Copyright 2026 Lscythe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.lscythe.app.navigo.core.designsystem.token

import androidx.compose.ui.graphics.Color

// Light color scheme
val LightPrimaryColor = Color(0xFF0B3D33)
val LightOnPrimaryColor = Color(0xFFA3E635)
val LightPrimaryContainerColor = Color(0xFFD7F5E4)
val LightOnPrimaryContainerColor = Color(0xFF04291F)
val LightInversePrimaryColor = Color(0xFF86D5B6)
val LightSecondaryColor = Color(0xFF0F6B48)
val LightOnSecondaryColor = Color(0xFFFFFFFF)
val LightSecondaryContainerColor = Color(0xFFC9EBD8)
val LightOnSecondaryContainerColor = Color(0xFF002114)
val LightTertiaryColor = Color(0xFF5C6C1A)
val LightOnTertiaryColor = Color(0xFFFFFFFF)
val LightTertiaryContainerColor = Color(0xFFE1ED92)
val LightOnTertiaryContainerColor = Color(0xFF1A2000)
val LightBackgroundColor = Color(0xFFF6FBF6)
val LightOnBackgroundColor = Color(0xFF191C1A)
val LightSurfaceColor = Color(0xFFF6FBF6)
val LightOnSurfaceColor = Color(0xFF191C1A)
val LightSurfaceVariantColor = Color(0xFFDBE5DD)
val LightOnSurfaceVariantColor = Color(0xFF3F4945)
val LightSurfaceTintColor = Color(0xFF0B3D33)
val LightInverseSurfaceColor = Color(0xFF2E3130)
val LightInverseOnSurfaceColor = Color(0xFFEFF1EE)
val LightErrorColor = Color(0xFFB3261E)
val LightOnErrorColor = Color(0xFFFFFFFF)
val LightErrorContainerColor = Color(0xFFF9DEDC)
val LightOnErrorContainerColor = Color(0xFF410E0B)
val LightOutlineColor = Color(0xFF6F7B76)
val LightOutlineVariantColor = Color(0xFFBFCAC4)
val LightScrimColor = Color(0xFF000000)
val LightSurfaceBrightColor = Color(0xFFF6FBF6)
val LightSurfaceContainerLowestColor = Color(0xFFFFFFFF)
val LightSurfaceContainerLowColor = Color(0xFFF0F6F1)
val LightSurfaceContainerColor = Color(0xFFEAF1EB)
val LightSurfaceContainerHighColor = Color(0xFFE4EBE6)
val LightSurfaceContainerHighestColor = Color(0xFFDEE6E0)
val LightSurfaceDimColor = Color(0xFFD6DDD7)
val LightPrimaryFixedColor = Color(0xFFD7F5E4)
val LightPrimaryFixedDimColor = Color(0xFF86D5B6)
val LightOnPrimaryFixedColor = Color(0xFF002117)
val LightOnPrimaryFixedVariantColor = Color(0xFF0B3D33)
val LightSecondaryFixedColor = Color(0xFFC9EBD8)
val LightSecondaryFixedDimColor = Color(0xFFADD0BC)
val LightOnSecondaryFixedColor = Color(0xFF002114)
val LightOnSecondaryFixedVariantColor = Color(0xFF005235)
val LightTertiaryFixedColor = Color(0xFFE1ED92)
val LightTertiaryFixedDimColor = Color(0xFFC5D079)
val LightOnTertiaryFixedColor = Color(0xFF1A2000)
val LightOnTertiaryFixedVariantColor = Color(0xFF444F03)
val LightOperatorColor = Color(0xFF7A5900)
val LightOperatorContainerColor = Color(0xFFFEF3C7)

// Dark color scheme
val DarkPrimaryColor = Color(0xFF86D5B6)
val DarkOnPrimaryColor = Color(0xFF003829)
val DarkPrimaryContainerColor = Color(0xFF00513C)
val DarkOnPrimaryContainerColor = Color(0xFFA3F3D2)
val DarkInversePrimaryColor = Color(0xFF0B3D33)
val DarkSecondaryColor = Color(0xFFADD0BC)
val DarkOnSecondaryColor = Color(0xFF173628)
val DarkSecondaryContainerColor = Color(0xFF2E4D3E)
val DarkOnSecondaryContainerColor = Color(0xFFC7EBD6)
val DarkTertiaryColor = Color(0xFFC5D079)
val DarkOnTertiaryColor = Color(0xFF2D3400)
val DarkTertiaryContainerColor = Color(0xFF434B00)
val DarkOnTertiaryContainerColor = Color(0xFFDEEA90)
val DarkBackgroundColor = Color(0xFF111413)
val DarkOnBackgroundColor = Color(0xFFE1E3E0)
val DarkSurfaceColor = Color(0xFF111413)
val DarkOnSurfaceColor = Color(0xFFE1E3E0)
val DarkSurfaceVariantColor = Color(0xFF3F4945)
val DarkOnSurfaceVariantColor = Color(0xFFBFC9C4)
val DarkSurfaceTintColor = Color(0xFF86D5B6)
val DarkInverseSurfaceColor = Color(0xFFE1E3E0)
val DarkInverseOnSurfaceColor = Color(0xFF2E3130)
val DarkErrorColor = Color(0xFFFFB4AB)
val DarkOnErrorColor = Color(0xFF690005)
val DarkErrorContainerColor = Color(0xFF93000A)
val DarkOnErrorContainerColor = Color(0xFFFFDAD6)
val DarkOutlineColor = Color(0xFF89938F)
val DarkOutlineVariantColor = Color(0xFF3F4945)
val DarkScrimColor = Color(0xFF000000)
val DarkSurfaceBrightColor = Color(0xFF363A38)
val DarkSurfaceContainerLowestColor = Color(0xFF0B0F0E)
val DarkSurfaceContainerLowColor = Color(0xFF191C1B)
val DarkSurfaceContainerColor = Color(0xFF1D201F)
val DarkSurfaceContainerHighColor = Color(0xFF272B29)
val DarkSurfaceContainerHighestColor = Color(0xFF323634)
val DarkSurfaceDimColor = Color(0xFF111413)
val DarkPrimaryFixedColor = Color(0xFFD7F5E4)
val DarkPrimaryFixedDimColor = Color(0xFF86D5B6)
val DarkOnPrimaryFixedColor = Color(0xFF002117)
val DarkOnPrimaryFixedVariantColor = Color(0xFF0B3D33)
val DarkSecondaryFixedColor = Color(0xFFC9EBD8)
val DarkSecondaryFixedDimColor = Color(0xFFADD0BC)
val DarkOnSecondaryFixedColor = Color(0xFF002114)
val DarkOnSecondaryFixedVariantColor = Color(0xFF005235)
val DarkTertiaryFixedColor = Color(0xFFE1ED92)
val DarkTertiaryFixedDimColor = Color(0xFFC5D079)
val DarkOnTertiaryFixedColor = Color(0xFF1A2000)
val DarkOnTertiaryFixedVariantColor = Color(0xFF444F03)
